import { z } from 'zod';

/**
 * Zod schema for over-age boolean attributes according to ISO 18013-5 Mobile Driving License.
 *
 * Each property represents whether the subject is over a specific age (from 0 to 99).
 * All properties are optional and correspond to the field "age_over_XX", e.g. age_over_21.
 *
 * - age_over_00: Indicates if the subject is over age 0.
 * - age_over_01: Indicates if the subject is over age 1.
 * - ...
 * - age_over_99: Indicates if the subject is over age 99.
 *
 * Example usage:
 * ```typescript
 * const value = { age_over_18: true, age_over_21: false };
 * overAgeSchema.parse(value); // Valid
 * ```
 */
export const overAgeSchema = z
  .object({
    age_over_00: z.boolean(),
    age_over_01: z.boolean(),
    age_over_02: z.boolean(),
    age_over_03: z.boolean(),
    age_over_04: z.boolean(),
    age_over_05: z.boolean(),
    age_over_06: z.boolean(),
    age_over_07: z.boolean(),
    age_over_08: z.boolean(),
    age_over_09: z.boolean(),
    age_over_10: z.boolean(),
    age_over_11: z.boolean(),
    age_over_12: z.boolean(),
    age_over_13: z.boolean(),
    age_over_14: z.boolean(),
    age_over_15: z.boolean(),
    age_over_16: z.boolean(),
    age_over_17: z.boolean(),
    age_over_18: z.boolean(),
    age_over_19: z.boolean(),
    age_over_20: z.boolean(),
    age_over_21: z.boolean(),
    age_over_22: z.boolean(),
    age_over_23: z.boolean(),
    age_over_24: z.boolean(),
    age_over_25: z.boolean(),
    age_over_26: z.boolean(),
    age_over_27: z.boolean(),
    age_over_28: z.boolean(),
    age_over_29: z.boolean(),
    age_over_30: z.boolean(),
    age_over_31: z.boolean(),
    age_over_32: z.boolean(),
    age_over_33: z.boolean(),
    age_over_34: z.boolean(),
    age_over_35: z.boolean(),
    age_over_36: z.boolean(),
    age_over_37: z.boolean(),
    age_over_38: z.boolean(),
    age_over_39: z.boolean(),
    age_over_40: z.boolean(),
    age_over_41: z.boolean(),
    age_over_42: z.boolean(),
    age_over_43: z.boolean(),
    age_over_44: z.boolean(),
    age_over_45: z.boolean(),
    age_over_46: z.boolean(),
    age_over_47: z.boolean(),
    age_over_48: z.boolean(),
    age_over_49: z.boolean(),
    age_over_50: z.boolean(),
    age_over_51: z.boolean(),
    age_over_52: z.boolean(),
    age_over_53: z.boolean(),
    age_over_54: z.boolean(),
    age_over_55: z.boolean(),
    age_over_56: z.boolean(),
    age_over_57: z.boolean(),
    age_over_58: z.boolean(),
    age_over_59: z.boolean(),
    age_over_60: z.boolean(),
    age_over_61: z.boolean(),
    age_over_62: z.boolean(),
    age_over_63: z.boolean(),
    age_over_64: z.boolean(),
    age_over_65: z.boolean(),
    age_over_66: z.boolean(),
    age_over_67: z.boolean(),
    age_over_68: z.boolean(),
    age_over_69: z.boolean(),
    age_over_70: z.boolean(),
    age_over_71: z.boolean(),
    age_over_72: z.boolean(),
    age_over_73: z.boolean(),
    age_over_74: z.boolean(),
    age_over_75: z.boolean(),
    age_over_76: z.boolean(),
    age_over_77: z.boolean(),
    age_over_78: z.boolean(),
    age_over_79: z.boolean(),
    age_over_80: z.boolean(),
    age_over_81: z.boolean(),
    age_over_82: z.boolean(),
    age_over_83: z.boolean(),
    age_over_84: z.boolean(),
    age_over_85: z.boolean(),
    age_over_86: z.boolean(),
    age_over_87: z.boolean(),
    age_over_88: z.boolean(),
    age_over_89: z.boolean(),
    age_over_90: z.boolean(),
    age_over_91: z.boolean(),
    age_over_92: z.boolean(),
    age_over_93: z.boolean(),
    age_over_94: z.boolean(),
    age_over_95: z.boolean(),
    age_over_96: z.boolean(),
    age_over_97: z.boolean(),
    age_over_98: z.boolean(),
    age_over_99: z.boolean(),
  })
  .partial();
